/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class HeavyPluginAudioProcessorEditor  :  public AudioProcessorEditor,
                                          private Slider::Listener
{
public:
    HeavyPluginAudioProcessorEditor (HeavyPluginAudioProcessor&);
    ~HeavyPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    void sliderValueChanged (Slider* slider) override;

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    HeavyPluginAudioProcessor& processor;
  
    ScopedPointer<Label> pitchLabel;
    ScopedPointer<Slider> pitchSlider;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (HeavyPluginAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
