/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_SAMPLEPLAYER_H_
#define _HEAVYCONTEXT_SAMPLEPLAYER_H_

#include "HvBase.h"

#define Context(_x) ((Hv_samplePlayer *) (_x))

// object includes
#include "ControlSystem.h"
#include "SignalVar.h"
#include "ControlCast.h"
#include "HvTable.h"
#include "ControlSlice.h"
#include "SignalTabread.h"
#include "HeavyMath.h"
#include "ControlBinop.h"
#include "ControlVar.h"
#include "SignalPhasor.h"

typedef struct Hv_samplePlayer {
  HvBase base;

  // objects
  SignalPhasor sPhasor_4LJvR;
  SignalVarf sVarf_WITUz;
  SignalVarf sVarf_wniAO;
  SignalVarf sVarf_3GfUj;
  SignalVarf sVarf_d5fW8;
  SignalVarf sVarf_slemn;
  SignalTabread sTabread_3YBRA;
  SignalVarf sVarf_OSFIN;
  SignalTabread sTabread_gZy9y;
  SignalVarf sVarf_XcY5N;
  SignalVarf sVarf_TU8b5;
  ControlBinop cBinop_eGPmi;
  ControlBinop cBinop_HwAvW;
  ControlBinop cBinop_vzC8w;
  ControlVar cVar_Wwrrg;
  ControlVar cVar_Q0ljM;
  ControlSlice cSlice_lNr2Z;
  ControlBinop cBinop_hnwCx;
  ControlVar cVar_3ztk8;
  HvTable hTable_bXzso;
} Hv_samplePlayer;

#endif // _HEAVYCONTEXT_SAMPLEPLAYER_H_
