/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "HvContext_samplePlayer.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */

static void cReceive_2yzdV_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_WJrb0_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_eGPmi_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_Xy22a_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_HwAvW_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_54pfm_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_vzC8w_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_AXXiY_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_rPEXX_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_Wwrrg_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_Q0ljM_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_jl4Op_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_zRDIH_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cSlice_lNr2Z_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_gpsLI_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_hnwCx_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_r41TC_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_lxBfo_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_Tknye_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_3ztk8_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_btOyB_sendMessage(HvBase *, int, const HvMessage *const);
static void hTable_bXzso_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_8M8bD_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0x149567EC: { // "table-size"
      ctx_scheduleMessage(_c, m, &cReceive_54pfm_sendMessage, 0);
      ctx_scheduleMessage(_c, m, &cReceive_AXXiY_sendMessage, 0);
      break;
    }
    case 0x29E4A0EF: { // "speed"
      ctx_scheduleMessage(_c, m, &cReceive_2yzdV_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    case 0x1812752E: return &Context(_c)->hTable_bXzso; // "test"
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_samplePlayer *hv_samplePlayer_new(double sampleRate) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  Hv_samplePlayer *const _c = (Hv_samplePlayer *) hv_malloc(sizeof(Hv_samplePlayer));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, 10); // 10KB MessagePool
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "samplePlayer";

  Base(_c)->numBytes = sizeof(Hv_samplePlayer);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_4LJvR, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_WITUz, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_wniAO, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_3GfUj, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_d5fW8, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_slemn, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_3YBRA, &_c->hTable_bXzso, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_OSFIN, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_gZy9y, &_c->hTable_bXzso, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_XcY5N, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_TU8b5, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_HwAvW, 0.0f); // __div
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_vzC8w, 1.0f); // __mul
  Base(_c)->numBytes += cVar_init_s(&_c->cVar_Wwrrg, "test");
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_Q0ljM, 0.0f);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_lNr2Z, 1, 1);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_3ztk8, 0.0f);
  Base(_c)->numBytes += hTable_init(&_c->hTable_bXzso, 100);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_jl4Op_sendMessage, 0);

  return _c;
}

void hv_samplePlayer_free(Hv_samplePlayer *_c) {
  hTable_free(&_c->hTable_bXzso);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */

static void cReceive_2yzdV_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_8M8bD_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_btOyB_sendMessage);
}
static void cMsg_WJrb0_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 0.0f, 0, m, &cBinop_eGPmi_sendMessage);
}
static void cBinop_eGPmi_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3ztk8, 0, m, &cVar_3ztk8_sendMessage);
}
static void cCast_Xy22a_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_lxBfo_sendMessage(_c, 0, m);
}
static void cBinop_HwAvW_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_WJrb0_sendMessage(_c, 0, m);
}
static void cReceive_54pfm_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_WITUz, m);
}
static void cBinop_vzC8w_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_4LJvR, 0, m);
}
static void cReceive_AXXiY_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_Xy22a_sendMessage);
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_rPEXX_sendMessage);
}
static void cCast_rPEXX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_HwAvW, HV_BINOP_DIVIDE, 0, m, &cBinop_HwAvW_sendMessage);
}
static void cVar_Wwrrg_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_gpsLI_sendMessage(_c, 0, m);
}
static void cVar_Q0ljM_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 2.0f, 0, m, &cBinop_hnwCx_sendMessage);
}
static void cLoadbang_jl4Op_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_Wwrrg, 0, m, &cVar_Wwrrg_sendMessage);
}
static void cSwitchcase_zRDIH_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x3E004DAB: { // "set"
      cSlice_onMessage(_c, &Context(_c)->cSlice_lNr2Z, 0, m, &cSlice_lNr2Z_sendMessage);
      break;
    }
    default: {
      break;
    }
  }
}
static void cSlice_lNr2Z_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sTabread_onMessage(_c, &Context(_c)->sTabread_3YBRA, 1, m);
  sTabread_onMessage(_c, &Context(_c)->sTabread_gZy9y, 1, m);
  cVar_onMessage(_c, &Context(_c)->cVar_Wwrrg, 0, m, &cVar_Wwrrg_sendMessage);
}
static void cMsg_gpsLI_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(3);
  msg_init(m, 3, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "table");
  msg_setElementToFrom(m, 1, n, 0);
  msg_setSymbol(m, 2, "size");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_r41TC_sendMessage);
}
static void cBinop_hnwCx_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_slemn, m);
}
static void cSystem_r41TC_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 2.0f, 0, m, &cBinop_hnwCx_sendMessage);
}
static void cMsg_lxBfo_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_Tknye_sendMessage);
}
static void cSystem_Tknye_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_HwAvW, HV_BINOP_DIVIDE, 1, m, &cBinop_HwAvW_sendMessage);
}
static void cVar_3ztk8_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_vzC8w, HV_BINOP_MULTIPLY, 0, m, &cBinop_vzC8w_sendMessage);
}
static void cCast_btOyB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3ztk8, 0, m, &cVar_3ztk8_sendMessage);
}
static void hTable_bXzso_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}
static void cCast_8M8bD_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_vzC8w, HV_BINOP_MULTIPLY, 1, m, &cBinop_vzC8w_sendMessage);
}



/*
 * Context Process Implementation
 */

int hv_samplePlayer_process(Hv_samplePlayer *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4;
  hv_bufferi_t Bi0, Bi1;

  // input and output vars
  // no input channels
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    // no input channels

    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_4LJvR, VOf(Bf0));
    __hv_var_f(&_c->sVarf_WITUz, VOf(Bf1));
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_var_f(&_c->sVarf_wniAO, VOf(Bf0));
    __hv_var_f(&_c->sVarf_3GfUj, VOf(Bf2));
    __hv_var_f(&_c->sVarf_d5fW8, VOf(Bf3));
    __hv_add_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_slemn, VOf(Bf4));
    __hv_min_f(VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_add_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf2), 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
    __hv_max_f(VIf(Bf4), VIf(Bf2), VOf(Bf2));
    __hv_cast_fi(VIf(Bf2), VOi(Bi0));
    __hv_var_k_i(VOi(Bi1), 1, 1, 1, 1, 1, 1, 1, 1, 0);
    __hv_add_i(VIi(Bi0), VIi(Bi1), VOi(Bi1));
    __hv_tabread_if(&_c->sTabread_3YBRA, VIi(Bi1), VOf(Bf4));
    __hv_var_f(&_c->sVarf_OSFIN, VOf(Bf3));
    __hv_add_f(VIf(Bf4), VIf(Bf3), VOf(Bf3));
    __hv_tabread_if(&_c->sTabread_gZy9y, VIi(Bi0), VOf(Bf4));
    __hv_sub_f(VIf(Bf3), VIf(Bf4), VOf(Bf3));
    __hv_add_f(VIf(Bf0), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_XcY5N, VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(Bf2), VOf(Bf0));
    __hv_floor_f(VIf(Bf2), VOf(Bf2));
    __hv_sub_f(VIf(Bf0), VIf(Bf2), VOf(Bf2));
    __hv_var_f(&_c->sVarf_TU8b5, VOf(Bf0));
    __hv_add_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_fma_f(VIf(Bf3), VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf2), 0.707f, 0.707f, 0.707f, 0.707f, 0.707f, 0.707f, 0.707f, 0.707f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf2), VOf(Bf2));
    __hv_add_f(VIf(Bf2), VIf(O1), VOf(O1));
    __hv_add_f(VIf(Bf2), VIf(O0), VOf(O0));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

int hv_samplePlayer_process_inline(Hv_samplePlayer *c, float *const inputBuffers, float *const outputBuffers, int n4) {
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_samplePlayer_process(c, bIn, bOut, n4);
  return n;
}
