/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_EXAMPLEPATCH1_H_
#define _HEAVYCONTEXT_EXAMPLEPATCH1_H_

#include "HvBase.h"

#define Context(_x) ((Hv_ExamplePatch1 *) (_x))

// object includes
#include "SignalTabwrite.h"
#include "HvTable.h"
#include "SignalVar.h"
#include "ControlCast.h"
#include "ControlSystem.h"
#include "ControlTabhead.h"
#include "ControlIf.h"
#include "SignalTabread.h"
#include "HeavyMath.h"
#include "ControlBinop.h"
#include "ControlDelay.h"
#include "ControlVar.h"

typedef struct Hv_ExamplePatch1 {
  HvBase base;

  // objects
  SignalTabread sTabread_Hqi5g;
  SignalTabwrite sTabwrite_LZKYO;
  ControlTabhead cTabhead_Ji7pw;
  ControlBinop cBinop_OMovE;
  ControlBinop cBinop_o0vf6;
  ControlBinop cBinop_yDxXV;
  ControlDelay cDelay_mgpqj;
  ControlBinop cBinop_UCT4O;
  ControlIf cIf_Hchwi;
  ControlBinop cBinop_RxWyq;
  ControlBinop cBinop_X0bNe;
  ControlDelay cDelay_DNLQl;
  ControlBinop cBinop_hduOb;
  ControlVar cVar_ntMXo;
  ControlDelay cDelay_6UqWb;
  ControlBinop cBinop_byqqR;
  ControlBinop cBinop_7oAye;
  HvTable hTable_WKE6m;
} Hv_ExamplePatch1;

#endif // _HEAVYCONTEXT_EXAMPLEPATCH1_H_
